version: 2
jobs:
 build:
   machine: true
   steps:
     - checkout

     # build image
     - run: |
         docker info
         docker build -t aspnetapp DotNetCoreSampleApi
     # unit test
     - run: |
         docker-compose -f docker-compose.unittests.yml run --rm unittests
